### ISSUE TITLE
python client: URL has no propper form: http://zeus:8080

### ISSUE THREAD

**Issue by WolfgangFahl** [semi-technologies/weaviate#1216]
taken from https://www.semi.technology/documentation/weaviate/current/client-libs/python.html example and replaced "localhost" with "zeus":

``` 
def testWeaviate(self):

        client = weaviate.Client("http://zeus:8080")
        client.create_schema("https://raw.githubusercontent.com/semi-technologies/weaviate-python-client/master/documentation/getting_started/people_schema.json")

        pass
```

result:
```
ERROR: testWeaviate (test.testWeaviate.TestWeaviate)
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/wf/Documents/pyworkspace/dgraphtest/test/testWeaviate.py", line 22, in testWeaviate
    client = weaviate.Client("http://zeus:8080")
  File "/Users/wf/Library/Python/3.8/lib/python/site-packages/weaviate/client.py", line 56, in __init__
    raise ValueError("URL has no propper form: " + url)
ValueError: URL has no propper form: http://zeus:8080
```

tried to debug this but the code has some indirection that makes debugging hard - so I could not find out what "proper" means. I'd appreciate if the example would have a "proper" form and the error message would state examples for "proper" forms as well as the rules for "proper" form. For what's it worth the url http://zeus:8080 returns:

```
{
	"links": [{
		"href": "/v1/meta",
		"name": "Meta information about this instance/cluster"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/add-data/define_schema.html",
		"href": "/v1/schema",
		"name": "view complete schema"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/add-data/define_schema.html",
		"href": "/v1/schema/things{/:className}",
		"name": "CRUD things schema"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/add-data/define_schema.html",
		"href": "/v1/schema/actions{/:className}",
		"name": "CRUD actions schema"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/add-data/add_and_modify.html",
		"href": "/v1/things{/:id}",
		"name": "CRUD things"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/add-data/add_and_modify.html",
		"href": "/v1/actions{/:id}",
		"name": "CRUD actions"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/features/contextual-classification.html,https://www.semi.technology/documentation/weaviate/current/features/knn-classification.html",
		"href": "/v1/classifications{/:id}",
		"name": "trigger and view status of classifications"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/features/adding-synonyms.html",
		"href": "/v1/c11y/concepts/:concept",
		"name": "search contextionary for concepts"
	}, {
		"documentationHref": "https://www.semi.technology/documentation/weaviate/current/features/adding-synonyms.html",
		"href": "/v1/c11y/extensions",
		"name": "extend contextionary with custom extensions"
	}]
}
```

Which doesn't look like it's not part of Weaviate's "proper" world. The result is from the MacOS machine mentioned in #1215

**Comment by WolfgangFahl** [comment]
As as a workaround i used the numerical IP of the host. This is really astonishing ... why on earth wouldn't i be able to use a proper domain name when the example uses localhost and not 127.0.0.1?

**Comment by fefi42** [comment]
Hello @WolfgangFahl thank you very much for your report.
I opened an issue at the python client project: https://github.com/semi-technologies/weaviate-python-client/issues/37
This will be fixed beginning of next week.

Closing this issue in favor of the other one.
