### ISSUE TITLE
Bug: deleting a class which has a running classification leads to a panic

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1396]
Using the classification setup from the weaviate-javascript-client e2e test, the following panic occurs:

```
panic: trying to delete nil node 0 of parent 0 (0.094482)


goroutine 327 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*binarySearchNodeGeneric).delete(0x0, 0x0, 0x0, 0xc0009d5a40)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/binary_search_tree.go:232 +0x3ee
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*binarySearchNodeGeneric).delete(0xc0009d5a40, 0x0, 0x0, 0xc0009d59e0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/binary_search_tree.go:279 +0x295
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*binarySearchNodeGeneric).delete(0xc0009d59e0, 0x0, 0x0, 0xc0009d5a80)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/binary_search_tree.go:282 +0x2bc
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*binarySearchTreeGeneric).delete(0xc0004e67a0, 0x0, 0x0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/binary_search_tree.go:78 +0x91
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findAndConnectNeighbors(0xc000a32000, 0xc000be9aa0, 0x3, 0xc000c0af00, 0x12c, 0x12c, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/index.go:464 +0x701
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).insert(0xc000a32000, 0xc000be9aa0, 0xc000c0af00, 0x12c, 0x12c, 0xc000b56000, 0xc000b2f501)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/index.go:335 +0x2ea
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).Add(0xc000a32000, 0x0, 0xc000c0af00, 0x12c, 0x12c, 0xc000ae1e88, 0x10075ab)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/index.go:267 +0xc1
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).updateVectorIndex(0xc000a83ec0, 0xc000c0af00, 0x12c, 0x12c, 0x0, 0xc000b56100, 0x0, 0xc000413620, 0xc000c50580)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_write_put.go:65 +0x7f
github.com/semi-technologies/weaviate/adapters/repos/db.(*objectsBatcher).storeSingleObjectInAdditionalStorage(0xc000c50540, 0x1edb0c0, 0xc000b52720, 0xc000b3cd10, 0x0, 0xc00062f100, 0x0, 0x0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_write_batch_objects.go:209 +0xa6
github.com/semi-technologies/weaviate/adapters/repos/db.(*objectsBatcher).storeAdditionalStorage.func1(0xc0004515f0, 0xc000c50540, 0x1edb0c0, 0xc000b52720, 0xc000b3cd10, 0x0, 0x0, 0x0, 0x0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_write_batch_objects.go:179 +0xbf
created by github.com/semi-technologies/weaviate/adapters/repos/db.(*objectsBatcher).storeAdditionalStorage
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_write_batch_objects.go:177 +0x211
```

**Comment by etiennedi** [comment]
## Cause
We've been able to narrow this down to the following (copy/paste from Slack):

- The JS client has (like the python client) an ability to wait for an ongoing classification (so the user doesn't have to poll manually)
- The last test in the JS test suite test that if the user sets a timeout which is too small for the wait function that it errors
- Immediately after the last test finishes, the cleanup is called (which deletes all classes)
- Because we explicitly set the timeout so low, the classification is still ongoing
- Weaviate does not cancel ongoing classifications, but simply deletes the class, so the classification is still running on a class which doesn't exist <-- This is the bug

## Fix
When deleting classes and there are still ongoing classifications, explicitly cancel them. This should be quite easy, since they already use a context, so this might be possible by using a simple `context.Cancel()`
