### ISSUE TITLE
[1.5.0-rc.X] Segmentation Violation when running Aggregation during import

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1617]
```
unexpected fault address 0x2f48a2b4
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f48a2b4 pc=0x1074265]

goroutine 40979 [running]:
runtime.throw(0x1c4456e, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc01f515920 sp=0xc01f5158f0 pc=0x10394b2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x276 fp=0xc01f515958 sp=0xc01f515920 pc=0x1050d56
runtime.memmove(0xc01f5b0800, 0x2f489bb6, 0x77e)
        /usr/local/go/src/runtime/memmove_amd64.s:332 +0x3c5 fp=0xc01f515960 sp=0xc01f515958 pc=0x1074265
bytes.(*Reader).Read(0xc01f8af0b0, 0xc01f5b0800, 0x77e, 0x7e4, 0x1aa7620, 0xc014deb128, 0x0)
        /usr/local/go/src/bytes/reader.go:45 +0xb1 fp=0xc01f515990 sp=0xc01f515960 pc=0x1100991
```

**Comment by etiennedi** [comment]
Was caused by a missing lock that lead to an aggregation starting a cursor on a segment which was removed by compaction before the cursor completed. These things cannot happen at the same time. Either the compaction process needs to wait for the cursor or vice-versa. Has been fixed through the `segmentGroup.maintenanceLock` which is an RWLock.
