### ISSUE TITLE
C11y container fails at around 1M data objects

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1644]
I'm adding a large dataset with contextionary vectorization to Weaviate but at some point (around 1M objects), the contextionary container (compound splitting enabled) fails with:

```
goroutine 10050 [running]:
github.com/semi-technologies/contextionary/contextionary/core.(*Wordlist).getWordPtr(0xc00002ecc0, 0xc7b98, 0x20, 0x7f81e27fc95c, 0x5)
	/app/contextionary/core/wordlist.go:140 +0x88
github.com/semi-technologies/contextionary/contextionary/core.(*Wordlist).FindIndexByWord(0xc00002ecc0, 0xc000731014, 0x4, 0xc0006f1c20)
	/app/contextionary/core/wordlist.go:109 +0x169
github.com/semi-technologies/contextionary/contextionary/core.(*mmappedIndex).WordToItemIndex(0xc000078000, 0xc000731014, 0x4, 0x0)
	/app/contextionary/core/mmapped.go:42 +0x42
main.(*Vectorizer).vectorForLibraryWord(0xc000ad4100, 0xc000731014, 0x4, 0x0, 0x0, 0x0)
	/app/server/corpus_vectorizer.go:282 +0x161
main.(*Vectorizer).VectorForWord(0xc000ad4100, 0xc000731014, 0x4, 0xaacfb1, 0x1, 0xc000731014)
	/app/server/corpus_vectorizer.go:246 +0x2dc
main.(*Vectorizer).vectorsAndOccurrences(0xc000ad4100, 0xc00077a000, 0x1120, 0x1120, 0x90, 0x91, 0x9a, 0x9b, 0xa3, 0xa4, ...)
	/app/server/corpus_vectorizer.go:200 +0x129
main.(*Vectorizer).vectorForWords(0xc000ad4100, 0xc00077a000, 0x1120, 0x1120, 0xc0006f3850, 0xc00077a000, 0x1120, 0x1120)
	/app/server/corpus_vectorizer.go:140 +0x67
main.(*Vectorizer).vectorForWordOrWords(0xc000ad4100, 0xc00077a000, 0x1120, 0x1120, 0xc00069b850, 0x1120, 0x1, 0x0)
	/app/server/corpus_vectorizer.go:127 +0xb8
main.(*Vectorizer).Corpi(0xc000ad4100, 0xc00020e660, 0x1, 0x1, 0xc0006f3850, 0x0, 0xc000180100, 0x0)
	/app/server/corpus_vectorizer.go:101 +0x285
main.(*server).VectorForCorpi(0xc00014ee00, 0xb76420, 0xc0002e0150, 0xc000a6eaa0, 0xc00014ee00, 0xc0002e0150, 0xc000a22a80)
	/app/server/api.go:160 +0x89
github.com/semi-technologies/contextionary/contextionary._Contextionary_VectorForCorpi_Handler(0xa8c900, 0xc00014ee00, 0xb76420, 0xc0002e0150, 0xc006318300, 0x0, 0xb76420, 0xc0002e0150, 0xc000728000, 0x6f01)
	/app/contextionary/contextionary.pb.go:1523 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c8420, 0xb7c040, 0xc000808d80, 0xc000180100, 0xc000a8a4e0, 0xf181d0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0000c8420, 0xb7c040, 0xc000808d80, 0xc000180100, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00061d870, 0xc0000c8420, 0xb7c040, 0xc000808d80, 0xc000180100)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```

**Comment by etiennedi** [comment]
The printed stack is showing what the specified goroutine `10050` was doing when a crash (most likely a panic) occurred, but not the cause of the crash. So unfortunately, it's impossible to tell what caused this based on the logs.

**Comment by bobvanluijt** [comment]
O - that's unfortunate. I'll try to find more information next time. Thx
