### ISSUE TITLE
[1.8.0-rc.x] Bug: Specifying the wrong data type on filters can lead to panics

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1750]
Needs to be fixed before 1.8.0 stable release.

Thanks to @cdpierse for discovering this:

```
cinegraph-populator-weaviate-1          | panic: SetCursor() called on strategy other than 'set'
cinegraph-populator-weaviate-1          | 
cinegraph-populator-weaviate-1          | goroutine 610 [running]:
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).SetCursor(0xc0004c4e00, 0x203000)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/cursor_bucket_set.go:44 +0x3b9
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*RowReader).greaterThan(0xc003f0f680, 0x1483a10, 0xc000132048, 0xc003f0f6a8, 0x40d500, 0x0, 0x0)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/row_reader.go:105 +0x5f
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*RowReader).Read(0xc003e86680, 0x1483a10, 0xc000132048, 0xc003e866a8, 0x1008960, 0xc003b4e0a8)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/row_reader.go:70 +0xf2
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*Searcher).docPointersInvertedNoFrequency(0xc003e86c90, 0xc003b7e858, 0x15, 0xc0004c4e00, 0xffffffffffffffff, 0xc003b46240, 0xc003e86701, 0x0, 0x0, 0x0, ...)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/searcher_doc_pointers.go:56 +0x173
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*Searcher).docPointersInverted(0xc003e86c90, 0xc003b7e858, 0x15, 0xc0004c4e00, 0xffffffffffffffff, 0xc003b46240, 0x7f495a0d9001, 0x0, 0x0, 0x0, ...)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/searcher_doc_pointers.go:46 +0x23d
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*Searcher).docPointers(0xc003e86c90, 0xc003b7e858, 0x15, 0xc0004c4e00, 0xffffffffffffffff, 0xc003b46240, 0x1, 0x0, 0x0, 0x0, ...)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/searcher_doc_pointers.go:36 +0x1fe
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*propValuePair).fetchDocIDs(0xc003b46240, 0xc003e86c90, 0xffffffffffffffff, 0x1, 0xc003b46240, 0x0)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/prop_value_pairs.go:57 +0x1b9
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*Searcher).DocIDs(0xc003e86c90, 0x1483a80, 0xc003e8e300, 0xc0026ad7e0, 0x1000000, 0x0, 0xc000800590, 0x8, 0x60, 0xc000d7ca20, ...)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/searcher.go:147 +0x9a
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).objectVectorSearch(0xc00019c070, 0x1483a80, 0xc003e8e300, 0xc003f00000, 0x300, 0x42a, 0x64, 0xc0026ad7e0, 0x1000000, 0x0, ...)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:191 +0x830
cinegraph-populator-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db.(*Index).objectVectorSearch.func1(0xffffffffffffffff, 0xc0012057b8)
cinegraph-populator-weaviate-1          |       /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/index.go:562 +0x210
cinegraph-populator-weaviate-1          | golang.org/x/sync/errgroup.(*Group).Go.func1(0xc003b42270, 0xc003f08000)
cinegraph-populator-weaviate-1          |       /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
cinegraph-populator-weaviate-1          | created by golang.org/x/sync/errgroup.(*Group).Go
cinegraph-populator-weaviate-1          |       /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
cinegraph-populator-weaviate-1 exited with code 2
```

**Comment by etiennedi** [comment]
The initial investigation has shown the following causes:

* We seem to be missing validation around data types and `value<>` fields. For example, the above is caused by using `valueDate` on type `text`
* when using only `where` filters panics are caught (leading to the panic message being displayed in the GraphQL error response), however a lock seems not to be released, blocking future queries
* All invalid combinations (map<>set and set<>map) lead to undefined behavior with panics in the worst case. This needs to be validated correctly.
