### ISSUE TITLE
`where` filter with 2 `And`ed  `Like` clauses and a `nearText` filter causes weaviate to panic.

### ISSUE THREAD

**Issue by StefanBogdan** [semi-technologies/weaviate#1772]
minimal setup to reproduce it.

Tested with:
- Weaviate version `v1.8.0` and `v1.9.0`
- With, and without, Usage Proxy.
- With `contextionary` and `transformers`

Everything gave same result.

This is the ONLY class needed to reproduce it.
```
class_schema = {
    'class': 'Test',
    'description': '',
    'properties':[
        {
            'name': 'testOne',
            'dataType': ['text']
        },
        {
            'name': 'testTwo',
            'dataType': ['text']
        }
    ]
}
```

And only one object is enough:
```
{
        'testOne': 'test tests',
        'testTwo': 'test'
    }
```
Now if you do this query:
```
{
  Get
  {
    Test(
      nearText:{
        concepts: ["ANYTHING YOU CAN COME UP WITH, DOES NOT MATTER  BUT IT HAS TO BE AT LEAST SOMETHING"]
      }
      where:{
        operator: And,
        operands:[
          {
            operator: Like,
            path: ["testOne"],
            valueText:"test*"
          },
          {
            operator: Like,
            path: ["testTwo"],
            valueText:"test*"
          }
        ]
      }
    ) {
      testOne
      testTwo
    }
  }
}
```
the weaviate crashes with this Console output:
```
{
  "message": "Failed to fetch",
  "stack": "TypeError: Failed to fetch\n    at https://console.semi.technology/static/js/main.7c685d2a.chunk.js:1:45268\n    at u (https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:981576)\n    at Generator._invoke (https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:981364)\n    at Generator.next (https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:982001)\n    at r (https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:302901)\n    at s (https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:303104)\n    at https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:303163\n    at new Promise (<anonymous>)\n    at https://console.semi.technology/static/js/2.94e923c7.chunk.js:2:303044\n    at fetcher (https://console.semi.technology/static/js/main.7c685d2a.chunk.js:1:45732)"
}
```
and these `weaviate` panic logs:
```
test-t2v-transformers-1  | INFO:     172.24.0.3:51112 - "POST /vectors HTTP/1.1" 307 Temporary Redirect
test-t2v-transformers-1  | INFO:     172.24.0.3:51112 - "POST /vectors/ HTTP/1.1" 200 OK
test-weaviate-1          | panic: runtime error: index out of range [1] with length 1
test-weaviate-1          | 
test-weaviate-1          | goroutine 595 [running]:
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.intersectAnd(0xc000d79ab0, 0xc000d79990, 0xc000de9a28)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/merge.go:95 +0x37e
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.mergeAndOptimized(0xc000dd20b0, 0x2, 0x2, 0x71183480e8645301, 0xc000d79a70, 0xc000dd20b0, 0xc000dc03f0)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/merge.go:72 +0x37f
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*propValuePair).mergeDocIDs(0xc000d79830, 0xc000de9c01, 0xffffffffffffffff, 0x1, 0x0)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/prop_value_pairs.go:88 +0x289
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db/inverted.(*Searcher).DocIDs(0xc000de9c88, 0x1486280, 0xc000bfabd0, 0xc000010a10, 0x0, 0x0, 0xc0002ed790, 0x4, 0x5638c8, 0x56385d, ...)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/inverted/searcher.go:169 +0xe8
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).objectVectorSearch(0xc00048d340, 0x1486280, 0xc000bfabd0, 0xc000dc4800, 0x180, 0x1da, 0x64, 0xc000010a10, 0x0, 0x0, ...)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:178 +0x84b
test-weaviate-1          | github.com/semi-technologies/weaviate/adapters/repos/db.(*Index).objectVectorSearch.func1(0x146f401, 0xc000e538c0)
test-weaviate-1          |      /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/index.go:562 +0x210
test-weaviate-1          | golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000dc0390, 0xc000cf7800)
test-weaviate-1          |      /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
test-weaviate-1          | created by golang.org/x/sync/errgroup.(*Group).Go
test-weaviate-1          |      /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
test-weaviate-1 exited with code 2
```
It fails only if we have both `where` and `nearText` filters set, if the root operator is `And` and if the wildcard is at the end of the word (for the `Like` operator).

The filters separately work fine.

It seem to fail when you have for the `Like` a `WORD*` and you use it in both properties, and one of the properties have the `WORD` twice but one of them has more characters appended (the order does not matter). For example:
- One property: `one onet`, second property: `one`, `WORD`: `one`
- One property: `something some`, second property: `some`, `WORD`: `some`

NOTE: You could add more words to each property, does not matter where, before, after or in-between, or any combination, as long as one property has the `WORD` only and the other the `WORD` and the `WORD` with some appended characters. One of the properties should NOT contain the `WORD` with appended characters (otherwise it works). Here is a another object that has the same behaviour:
```
{
  'testOne': 'this is a test that tests something',
  'testTwo': 'this is a test for fun'
}
# the WORD is 'test'
```

This is everything I have found out. I hope it helps

**Comment by etiennedi** [comment]
closed in #1773
