### ISSUE TITLE
Bug: Race / Nil pointer panic getSegmentWithUpperBoundary -> Flaky test

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1872]
There seems to be a race-like condition which can be experienced through a flaky test that fails with something like:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15ea6a5]

goroutine 52 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*segment).get(0x0, 0xc0008fe005, 0x4, 0x98967b, 0x15dfcd3, 0x15dec11, 0x15e361a, 0x15b6d6c, 0x15b638f)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_replace_strategy.go:23 +0x65
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).getWithUpperSegmentBoundary(0xc0003af200, 0xc0008fe005, 0x4, 0x98967b, 0x11, 0x10b7122, 0x108cdb4, 0xc0008fefaa, 0x4, 0x1094bc0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_group.go:164 +0x13f
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).makeExistsOnLower.func1(0xc0008fe005, 0x4, 0x98967b, 0x1, 0x2cf5, 0x4)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_group.go:125 +0xe8
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*segment).initCountNetAdditions.func1(0xc0008fe005, 0x4, 0x98967b, 0x2b00)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment.go:163 +0x99
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*bufferedKeyAndTombstoneExtractor).flushAndCallback(0xc0008cf200)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_key_and_tombstone_extractor.go:149 +0x123
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*bufferedKeyAndTombstoneExtractor).do(0xc0008cf200)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_key_and_tombstone_extractor.go:68 +0x139
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*segment).initCountNetAdditions(0xc0005c6000, 0xc00000e180, 0x16, 0x714e)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment.go:180 +0x305
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.newSegment(0xc0000ac570, 0x2e, 0x1f23d10, 0xc0004568c0, 0xc00000e180, 0xc0000ac59b, 0x1cb7ab5, 0x3)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment.go:136 +0x891
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).add(0xc0003af200, 0xc0000ac570, 0x2e, 0x0, 0x0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_group.go:140 +0x15a
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).atomicallyAddDiskSegmentAndRemoveFlushing(0xc000407340, 0x0, 0x0)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket.go:577 +0x1ac
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).FlushAndSwitch(0xc000407340, 0x1, 0xc000000015)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket.go:555 +0x32f
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).initFlushCycle.func1(0xc000407340)
        /Users/etiennedilocker/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket.go:508 +0x5a5
created by github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).initFlushCycle
```

I believe the underlying cause to be a race-like condition where the segment state changes while this method runs, thus leading to a nil-segment. Even though the segment access is thread-safe, thus not making this a classical race, there still seems to be a temporarily invalid state, probably from a missing lock.

**Comment by etiennedi** [comment]
The above theory was incorrect and the actual cause was in the shutdown method:

![image](https://user-images.githubusercontent.com/8974479/159706724-797d9df7-f444-42c8-8471-d054ff385712.png)

1. shutdown closes each disk segment
1. shutdown sets each segment to nil
1. shutdown did not previously change the slice, so as of now `ig.segments` is filled with `nil, nil, nil, ...`
1. the next flush (memtable is flushed after disk is closed) would try to read from `ig.segments` which has a non-zero length, but all contents are nil
1. simply setting the slice to nil fixes the problem
