### ISSUE TITLE
lmskv crash recovery index out of range panic

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1903]
## Steps to reproduce
~~not known yet~~ we have a CI pipeline that reproduces it, see comment below

## Error message
Example 1:
```
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/cmd/weaviate-server/main.go:61 +0x4b4
2022-04-08 12:37:35 main.main()
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/server.go:69
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/configure_api.go:193 +0xd65
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/handlers/rest.configureAPI(0xc000134300, 0x0, 0x0)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/repo.go:42 +0x3f
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc00032c990, 0x14dbce8, 0xc0007901e0, 0xc0000f2d80, 0x14ede60)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/init.go:53 +0x425
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.(*DB).init(0xc00032c990, 0x14dbce8, 0xc0007901e0, 0xc000000180, 0xf8a0bb)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/index.go:104 +0x4c5
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.NewIndex(0x14dbce8, 0xc0007901e0, 0xc00003a016, 0x11, 0xc0006d25d0, 0x13, 0x2710, 0x50, 0x5a, 0xc0005ca000, ...)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard.go:150 +0x848
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.NewShard(0x14dbce8, 0xc0007901e0, 0xc00002e2c0, 0xc, 0xc0005fe000, 0x0, 0x0, 0x0)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_init_properties.go:41 +0x158
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).initProperties(0xc0005ca0a0, 0x3e, 0xc0001ec1c0)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard.go:299 +0x2ea
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).addProperty(0xc0005ca0a0, 0x14dbcb0, 0xc00013a048, 0xc0005c8000, 0x0, 0x0)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/store.go:80 +0x14b
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Store).CreateOrLoadBucket(0xc004328630, 0x14dbcb0, 0xc00013a048, 0xc00272e1e0, 0x13, 0xc000408358, 0x1, 0x1, 0x7f521330aba0, 0x30)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket.go:91 +0x250
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.NewBucket(0x14dbcb0, 0xc00013a048, 0xc000e7d630, 0x4a, 0x14edd70, 0xc0001a8230, 0xc000408358, 0x1, 0x1, 0xc00194e240, ...)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket_recover_from_wal.go:76 +0x87a
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).recoverFromCommitLogs(0xc000148370, 0x14dbcb0, 0xc00013a048, 0x14edd70, 0xc0001a8230)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/bucket.go:551 +0x245
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Bucket).FlushAndSwitch(0xc000148370, 0xc000000004, 0xc0008dbd68)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/memtable_flush.go:72 +0x2bf
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Memtable).flush(0xc000033ef0, 0x0, 0x0)
2022-04-08 12:37:35 	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_serialization.go:145 +0xc8a
2022-04-08 12:37:35 github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.segmentIndices.WriteTo(0x1b5ca10, 0x0, 0x0, 0x0, 0xc00220d6c0, 0x70, 0x14c1760, 0xc003859280, 0xc000e7d630, 0x4a, ...)
2022-04-08 12:37:35 goroutine 1 [running]:
2022-04-08 12:37:35 
2022-04-08 12:37:35 panic: runtime error: index out of range [-1]
```

Example 2:
```
eaviate-weaviate-1  | {"action":"lsm_recover_from_active_wal","class":"Companies","index":"companies","level":"warning","msg":"active write-ahead-log found. Did weaviate crash prior to this? Trying to recover...","path":"/var/lib/weaviate/companies_RCuNIk1gyKt3_lsm/property_cik/segment-1649106562789758128.wal","shard":"RCuNIk1gyKt3","time":"2022-04-04T21:10:23Z"}
weaviate-weaviate-1  | {"action":"lsm_recover_from_active_wal_success","class":"Companies","index":"companies","level":"info","msg":"successfully recovered from write-ahead-log","path":"/var/lib/weaviate/companies_RCuNIk1gyKt3_lsm/property_cik/segment-1649106562789758128.wal","shard":"RCuNIk1gyKt3","time":"2022-04-04T21:10:23Z"}
weaviate-weaviate-1  | panic: runtime error: index out of range [-1]
weaviate-weaviate-1  | 
weaviate-weaviate-1  | goroutine 1 [running]:
weaviate-weaviate-1  | github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.segmentIndices.WriteTo(0x1553548, 0x0, 0x0, 0x0, 0x400581ca20, 0x5f, 0xecb768, 0x401f0039c0, 0x4005a20dc0, 0x39, ...)
weaviate-weaviate-1  |  /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/segment_serialization.go:145 +0x96c
```

**Comment by etiennedi** [comment]
We've managed to reproduce this using a new stress test pipeline that puts more pressure on the LSM store than the vector index. [You can see a failing build here](https://app.travis-ci.com/github/semi-technologies/weaviate-chaos-engineering/jobs/566420407).

**Comment by etiennedi** [comment]
We have identified the root cause, it's an issue with recovering LSM "Map" commit logs because they were read as "Set" entries which led to issues later on. Still left to do before we can make a patch release:

- [ ] Identify why this was not caught by the Weaviate test setup and add new tests accordingly
- [ ] Test for issues at larger scale (manual run on large VM)
- [ ] Since this problem was not caught by the tests, investigate if there could be other, similar problems that we're also not aware of.
