### ISSUE TITLE
Store nil pointer when trying to obtain Bucket

### ISSUE THREAD

**Issue by antas-marcin** [semi-technologies/weaviate#1926]
```
/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:127 +0x53
created by github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).registerTombstoneCleanup
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:134 +0xda
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).registerTombstoneCleanup.func1(0xc0002917c0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:124 +0x75
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).CleanUpTombstonedNodes(0xc0002917c0, 0xc000087e20, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:185 +0x12c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf(0xc0002917c0, 0xc025867e90, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:72 +0x146
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).get(0xc0001a89a0, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0xc026300000, 0x414882, 0xc000087c10, 0x134292f6, 0x2cb502df8ee6daf0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:76 +0x4f
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).handleCacheMiss(0xc0001a89a0, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0xc026356000, 0xc026300000, 0x8000, 0xc026356000, 0x6)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:146 +0x75
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).vectorByIndexID(0xc000956000, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0x7f7011e1a520, 0x7f7011e1a498, 0x5, 0xa000, 0x7f7011e1a520)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/store.go:43
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Store).Bucket(...)
goroutine 597 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd39b15]
```
Happened after starting to upload images to weaviate using the schema described [here](https://weaviate.slack.com/archives/C02RRQP23K3/p1649417081186309?thread_ts=1649401366.132479&cid=C02RRQP23K3), it all went good for approx 14h and then this happened! Then after approx 6 min this happened:

```
/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:127 +0x53
created by github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).registerTombstoneCleanup
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:134 +0xda
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).registerTombstoneCleanup.func1(0xc000330280)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:124 +0x75
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).CleanUpTombstonedNodes(0xc000330280, 0xc026317620, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/delete.go:185 +0x12c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf(0xc000330280, 0xc0258f3e30, 0xc0262ff800, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:72 +0x146
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).get(0xc00037c460, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0xc0283d6000, 0x414882, 0xc000082c10, 0xa8b1006d, 0xe771b9b46a3f3441)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:76 +0x4f
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).handleCacheMiss(0xc00037c460, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0xc0283de000, 0xc0283d6000, 0x8000, 0xc0283de000, 0x1)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:146 +0x75
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).vectorByIndexID(0xc000488000, 0x14dd2f0, 0xc00013a040, 0x31dcf, 0x7fce96600180, 0x7fce966000f8, 0x5, 0xa000, 0x7fce96600180)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/store.go:43
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Store).Bucket(...)
goroutine 44 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd39b15]
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by antas-marcin** [comment]
I was able to reproduce this issue twice already, running this command:
```
go test -cpuprofile=cpu.out -timeout 3600s -count 800 -race -tags=integrationTest -run ^TestRestartJourney$ ./adapters/repos/db
```
log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100f636d0]

goroutine 432810 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv.(*Store).Bucket(...)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/lsmkv/store.go:43
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).vectorByIndexID(0xc084cf4780, {0x100711588?, 0xc039565c48?}, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:147 +0x140
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).handleCacheMiss(0xc06a346230, {0x10147bab8, 0xc0b11c4de0}, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:76 +0x64
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*shardedLockCache).get(0xc06a346230, {0x10147bab8, 0xc0b11c4de0}, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache.go:72 +0x18c
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*vectorCachePrefiller).prefillLevel(0xc039565fa0, {0x10147bab8, 0xc0b11c4de0?}, 0x0, 0x1e8480)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache_prefiller.go:101 +0x220
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*vectorCachePrefiller).Prefill(0xc039565fa0, {0x10147bab8, 0xc0b11c4de0}, 0xc140bbe788?)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/vector_cache_prefiller.go:50 +0x78
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).prefillCache.func1()
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:160 +0x100
created by github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).prefillCache
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:156 +0xc8
FAIL	github.com/semi-technologies/weaviate/adapters/repos/db	1540.601s
FAIL
```
