### ISSUE TITLE
Bug: Weaviate panics on filtered vector search

### ISSUE THREAD

**Issue by StefanBogdan** [semi-technologies/weaviate#1937]
The weaviate logs of the crashed weaviate:
```
panic: runtime error: index out of range [360640] with length 325000

goroutine 8531 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).flatSearch(0xc00014b2c0, 0xc0bec78000, 0x200, 0x200, 0x320, 0xc12bb8ff50, 0x4450f2f57d02, 0x2f9fda9e, 0x2f9fda9e00000000, 0x626ba9ba, ...)
        /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/flat_search.go:25 +0x465
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).SearchByVector(0xc00014b2c0, 0xc0bec78000, 0x200, 0x200, 0x320, 0xc12bb8ff50, 0xc12bb8ff50, 0x0, 0x0, 0xc1152ab0a0, ...)
        /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/search.go:71 +0x1dd
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).objectVectorSearch(0xc0001d0dc0, 0x14dd360, 0xc128cd4600, 0xc128f1ec00, 0x200, 0x2c7, 0x320, 0xc120eecf50, 0x1000000, 0x0, ...)
        /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:311 +0x106
github.com/semi-technologies/weaviate/adapters/repos/db.(*Shard).localObjectVectorSearch(0xc0001d0dc0, 0x14dd360, 0xc128cd4600, 0xc128f1ec00, 0x200, 0x2c7, 0x0, 0x320, 0xc120eecf50, 0x1000000, ...)
        /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard_read.go:198 +0x1ca
github.com/semi-technologies/weaviate/adapters/repos/db.(*Index).objectVectorSearch.func1(0xffffffffffffffff, 0xc128e5ebc0)
        /go/src/github.com/semi-technologies/weaviate/adapters/repos/db/index.go:724 +0x236
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc128563ef0, 0xc114874fc0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

![image](https://user-images.githubusercontent.com/17197768/165932449-d80a2ad9-c39f-4907-a477-b2c7617031c3.png)

Weaviate has a CLIP, t2v and spellchecker module. There are 317628 objects in the `ProductImage` class and 349000 in the `Product` class. 339 of those match the where filter.

**Comment by etiennedi** [comment]
Note (to the assignee) that there is also [a video with some more tech details around this issue on our internal Jira](https://semi-technology.atlassian.net/browse/WEAVIATE-106).
