### ISSUE TITLE
Single pod crash looping after data import

### ISSUE THREAD

**Issue by doug-route** [semi-technologies/weaviate#1944]
Environment:
K8s 1.21
Installed v1.12.2 with Helm

Resources
```
replicas: 13
resources:
  requests:
    cpu: '2000m'
    memory: '20Gi'
  limits:
    cpu: '3000m'
    memory: '24Gi'
```
 Schema
 ```
 {
    "classes": [
        {
            "class": "Product",
            "invertedIndexConfig": {
                "bm25": {
                    "b": 0.75,
                    "k1": 1.2
                },
                "cleanupIntervalSeconds": 60,
                "stopwords": {
                    "additions": null,
                    "preset": "en",
                    "removals": null
                }
            },
            "properties": [
                {
                    "dataType": [
                        "string"
                    ],
                    "name": "merchant_id",
                    "tokenization": "word"
                },
                {
                    "dataType": [
                        "string"
                    ],
                    "name": "image_url",
                    "tokenization": "word"
                }
            ],
            "shardingConfig": {
                "virtualPerPhysical": 128,
                "desiredCount": 13,
                "actualCount": 13,
                "desiredVirtualCount": 1664,
                "actualVirtualCount": 1664,
                "key": "_id",
                "strategy": "hash",
                "function": "murmur3"
            },
            "vectorIndexConfig": {
                "skip": false,
                "cleanupIntervalSeconds": 300,
                "maxConnections": 64,
                "efConstruction": 128,
                "ef": -1,
                "dynamicEfMin": 100,
                "dynamicEfMax": 500,
                "dynamicEfFactor": 8,
                "vectorCacheMaxObjects": 60000000000,
                "flatSearchCutoff": 40000
            },
            "vectorIndexType": "hnsw",
            "vectorizer": "none"
        }
    ]
}
```
Pod log
```
{"deprecation":{"apiType":"Configuration","id":"config-files","locations":null,"mitigation":"Configure Weaviate using environment variables.","msg":"use of deprecated command line argument --config-file","sinceTime":"2020-09-08T09:46:00.000Z","sinceVersion":"0.22.16","status":"deprecated"},"level":"warning","msg":"use of deprecated command line argument --config-file","time":"2022-05-05T23:20:06Z"}
{"action":"startup","default_vectorizer_module":"text2vec-contextionary","level":"info","msg":"the default vectorizer modules is set to \"text2vec-contextionary\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2022-05-05T23:20:06Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2022-05-05T23:20:06Z"}
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.growIndexToAccomodateNode(0xc01cf80000, 0x9eb10, 0x9eb10, 0x64f210200000000, 0x14ef4e0, 0xc0003f7650, 0xc000340360, 0xc025b29cc8, 0x1, 0x1, ...)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/maintainance.go:78 +0xb1
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*Deserializer).ReadNode(0xc0005c4018, 0x14c2d60, 0xc000340360, 0xc0001724c0, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/deserializer.go:145 +0x105
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*Deserializer).Do(0xc0005c4018, 0xc000340360, 0xc0001724c0, 0xc01de00000, 0xc0000c4270, 0x0, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/deserializer.go:84 +0x105
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).restoreFromDisk(0xc0002a17c0, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:74 +0x609
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).init(0xc0002a17c0, 0xc00003c016, 0x11, 0xc000908078, 0x14, 0xc000458090, 0xc0005c80c0, 0x14ef4e0, 0xc0003f7650, 0x14d97a8, ...)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/startup.go:28 +0x5b
github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw.New(0xc00003c016, 0x11, 0xc000908078, 0x14, 0xc000458090, 0xc0005c80c0, 0x14ef4e0, 0xc0003f7650, 0x14d97a8, 0x1b5ea10, ...)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/vector/hnsw/index.go:196 +0x49e
github.com/semi-technologies/weaviate/adapters/repos/db.NewShard(0x14dd328, 0xc0002b37a0, 0xc000517d40, 0xc, 0xc0002f40f0, 0x0, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/shard.go:92 +0xef8
github.com/semi-technologies/weaviate/adapters/repos/db.NewIndex(0x14dd328, 0xc0002b37a0, 0xc00003c016, 0x11, 0xc00021b6e0, 0x7, 0x2710, 0x50, 0x5a, 0xc0004720a0, ...)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/index.go:104 +0x4c5
github.com/semi-technologies/weaviate/adapters/repos/db.(*DB).init(0xc0005b85a0, 0x14dd328, 0xc0002b37a0, 0xc000000180, 0xf8af9b)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/init.go:53 +0x425
github.com/semi-technologies/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc0005b85a0, 0x14dd328, 0xc0002b37a0, 0xc00049c5a0, 0x14ef4e0)
	/go/src/github.com/semi-technologies/weaviate/adapters/repos/db/repo.go:42 +0x3f
github.com/semi-technologies/weaviate/adapters/handlers/rest.configureAPI(0xc0007b0000, 0x0, 0x0)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/configure_api.go:193 +0xd65
github.com/semi-technologies/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/server.go:69
main.main()
	/go/src/github.com/semi-technologies/weaviate/cmd/weaviate-server/main.go:61 +0x4b4
```

**Comment by etiennedi** [comment]
Thanks for creating this issue. Can you provide some more info please, especially for the following points:

* What was the cause of the restart? (The stack trace mentions `weaviate/adapters/repos/db/vector/hnsw/startup.go:28` which runs on startup). Was this restart planned or did a crash or something similar occur?
* Can you share some details about your setup? What kind of filesystem/disks were you using?
* What were you doing when the issue occured? 
* Is this reproducible?
* Can you share some code that reproduces this issue? 
* Can you share the full history of the logs including before this restart/crash?
