### ISSUE TITLE
Stuck batch posting: reassign neighbor edges: find and connect neighbors: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle

### ISSUE THREAD

**Issue by illagrenan** [semi-technologies/weaviate#1968]
👉 The environment, schema and data are the same as in this issue: https://github.com/semi-technologies/weaviate/issues/1897. The only difference is the version used, I'm now using https://github.com/semi-technologies/weaviate/releases/tag/v1.13.2.

I get this error when importing batches:

```ndjson
{"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2022-06-03T12:15:03Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/batch/objects","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
{"action":"hnsw_tombstone_cleanup","error":"reassign neighbor edges: find and connect neighbors: entrypoint was deleted in the object store, it has been flagged for cleanup and should be fixed in the next cleanup cycle","level":"error","msg":"tombstone cleanup errord","time":"2022-06-03T12:15:10Z"}
```

I tried restarting the instance but had no success.

My pseudocode for importing batches is as follows:

```python
for batch in batches:
    with InfiniteRetry:
        http_client.post(
            "/v1/batch/objects",
            batch,
            headers={"Content-Type": "application/json"}
        )
```

Because I don't want to skip any batch, I do endless retry. My logs show that some batches cannot be imported into Weaviate even after tens of minutes/hours. Perhaps an important note: My data is constantly changing. Every day I delete old data from Weaviate and add new data. So in my case, there may be a situation where I add data (today) that I deleted yesterday.

**Comment by etiennedi** [comment]
Hi @illagrenan,

thank you for the report. Could you provide a minimal, but end-2-end reproducing example please. Once we have some code that reproduces this issue, we can get started with the investigation and fix right away. Thank you!

**Comment by illagrenan** [comment]
Sorry for the late reply. I haven't forgotten about the issue :-) The problem is that I haven't managed to reliably replicate the issue yet. 

So far I've only figured out the following. I have imported about 5 million objects (60 GiB). From time to time I need to reimport all the data to change object properties: i.e. the object has the same ID and the same vector and different properties.

During this failing re-import I see the following log messages:

```
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7387176 to 7412176, took 28.515338ms\n","new_size":7412176,"previous_size":7387176,"time":"2022-06-24T08:33:58Z","took":28515338}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7412176 to 7437176, took 28.358227ms\n","new_size":7437176,"previous_size":7412176,"time":"2022-06-24T08:33:58Z","took":28358227}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7437176 to 7462176, took 28.58174ms\n","new_size":7462176,"previous_size":7437176,"time":"2022-06-24T08:33:58Z","took":28581740}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7462176 to 7487176, took 28.582047ms\n","new_size":7487176,"previous_size":7462176,"time":"2022-06-24T08:33:58Z","took":28582047}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7487176 to 7512176, took 28.856107ms\n","new_size":7512176,"previous_size":7487176,"time":"2022-06-24T08:33:58Z","took":28856107}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7512176 to 7537176, took 28.866474ms\n","new_size":7537176,"previous_size":7512176,"time":"2022-06-24T08:33:58Z","took":28866474}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7537176 to 7562176, took 29.038208ms\n","new_size":7562176,"previous_size":7537176,"time":"2022-06-24T08:33:58Z","took":29038208}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7562176 to 7587176, took 29.765151ms\n","new_size":7587176,"previous_size":7562176,"time":"2022-06-24T08:33:58Z","took":29765151}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7587176 to 7612176, took 28.949774ms\n","new_size":7612176,"previous_size":7587176,"time":"2022-06-24T08:33:58Z","took":28949774}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7612176 to 7637176, took 28.834541ms\n","new_size":7637176,"previous_size":7612176,"time":"2022-06-24T08:33:58Z","took":28834541}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7637176 to 7662176, took 29.420637ms\n","new_size":7662176,"previous_size":7637176,"time":"2022-06-24T08:33:58Z","took":29420637}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7662176 to 7687176, took 29.489086ms\n","new_size":7687176,"previous_size":7662176,"time":"2022-06-24T08:33:59Z","took":29489086}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7687176 to 7712176, took 29.640379ms\n","new_size":7712176,"previous_size":7687176,"time":"2022-06-24T08:33:59Z","took":29640379}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7712176 to 7737176, took 29.836738ms\n","new_size":7737176,"previous_size":7712176,"time":"2022-06-24T08:33:59Z","took":29836738}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7737176 to 7762176, took 29.884846ms\n","new_size":7762176,"previous_size":7737176,"time":"2022-06-24T08:33:59Z","took":29884846}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7762176 to 7787176, took 29.615936ms\n","new_size":7787176,"previous_size":7762176,"time":"2022-06-24T08:33:59Z","took":29615936}
weaviate {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2022-06-24T08:33:59Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/graphql","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7787176 to 7812176, took 30.095284ms\n","new_size":7812176,"previous_size":7787176,"time":"2022-06-24T08:33:59Z","took":30095284}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7812176 to 7837176, took 30.246147ms\n","new_size":7837176,"previous_size":7812176,"time":"2022-06-24T08:33:59Z","took":30246147}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7837176 to 7862176, took 30.236458ms\n","new_size":7862176,"previous_size":7837176,"time":"2022-06-24T08:33:59Z","took":30236458}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7862176 to 7887176, took 30.422305ms\n","new_size":7887176,"previous_size":7862176,"time":"2022-06-24T08:33:59Z","took":30422305}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7887176 to 7912176, took 30.429191ms\n","new_size":7912176,"previous_size":7887176,"time":"2022-06-24T08:33:59Z","took":30429191}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7912176 to 7937176, took 30.66088ms\n","new_size":7937176,"previous_size":7912176,"time":"2022-06-24T08:33:59Z","took":30660880}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7937176 to 7962176, took 30.324965ms\n","new_size":7962176,"previous_size":7937176,"time":"2022-06-24T08:33:59Z","took":30324965}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7962176 to 7987176, took 30.649607ms\n","new_size":7987176,"previous_size":7962176,"time":"2022-06-24T08:33:59Z","took":30649607}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7987176 to 8012176, took 31.070946ms\n","new_size":8012176,"previous_size":7987176,"time":"2022-06-24T08:33:59Z","took":31070946}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 8012176 to 8037176, took 31.032223ms\n","new_size":8037176,"previous_size":8012176,"time":"2022-06-24T08:33:59Z","took":31032223}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 8037176 to 8062176, took 31.133399ms\n","new_size":8062176,"previous_size":8037176,"time":"2022-06-24T08:34:00Z","took":31133399}
weaviate {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2022-06-24T08:34:00Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/batch/objects","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
weaviate {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 8062176 to 8087176, took 31.233537ms\n","new_size":8087176,"previous_size":8062176,"time":"2022-06-24T08:34:00Z","took":31233537}
weaviate 2022/06/24 08:34:05 http: panic serving 127.0.0.1:48108: write tcp 127.0.0.1:8080->127.0.0.1:48108: write: broken pipe
weaviate goroutine 399326 [running]:
weaviate net/http.(*conn).serve.func1(0xc393c0be00)
weaviate     /usr/local/go/src/net/http/server.go:1805 +0x153
weaviate panic(0x111c640, 0xcd44ba7e50)
weaviate     /usr/local/go/src/runtime/panic.go:971 +0x499
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreateOK).WriteResponse(0xc47d3d66f0, 0x1509378, 0xcab15f9ea0, 0x14f5f60, 0x13e8468)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create_responses.go:70 +0x14d
weaviate github.com/go-openapi/runtime/middleware.(*Context).Respond(0xcd8ea0f7a0, 0x1509378, 0xcab15f9ea0, 0xc456b9e500, 0xcd8eeeb2e0, 0x1, 0x1, 0xc3929a2c00, 0x10eebe0, 0xc47d3d66f0)
weaviate     /go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x579
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreate).ServeHTTP(0xcd8e9d6bd0, 0x1509378, 0xcab15f9ea0, 0xc3929a2e00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create.go:90 +0x3a6
weaviate github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2d00)
weaviate     /go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x75
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8ea75790, 0x1509378, 0xcab15f9ea0, 0xc3929a2d00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.makeSetupMiddlewares.func1.1(0x1509378, 0xcab15f9ea0, 0xc3929a2d00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:39 +0xb7
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8ead2960, 0x1509378, 0xcab15f9ea0, 0xc3929a2d00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x359
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f112f40, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/go-openapi/runtime/middleware.Redoc.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x293
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ac040, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/go-openapi/runtime/middleware.Spec.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x1a3
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ac080, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/rs/cors.(*Cors).Handler.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x1b1
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f113060, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0xcb
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1a5830, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddLogging.func1.1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:110 +0x2f4
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1a5860, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.addPreflight.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:124 +0x74
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ab710, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:159 +0xa7
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ab728, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.addHandleRoot.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:54 +0x8f
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ab740, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:75 +0xa8
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1a5890, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate github.com/semi-technologies/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1(0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:142 +0x2e4
weaviate net/http.HandlerFunc.ServeHTTP(0xcd8f1ab758, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2050 +0x44
weaviate net/http.serverHandler.ServeHTTP(0xc2e50b4620, 0x1509378, 0xcab15f9ea0, 0xc3929a2b00)
weaviate     /usr/local/go/src/net/http/server.go:2868 +0xa3
weaviate net/http.(*conn).serve(0xc393c0be00, 0x150d3c0, 0xc393ed80c0)
weaviate     /usr/local/go/src/net/http/server.go:1933 +0x8cd
weaviate created by net/http.(*Server).Serve
weaviate     /usr/local/go/src/net/http/server.go:2994 +0x39b
Stream closed EOF for weaviate/weaviate-statefulset-1 (download-hdf-container)
weaviate {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2022-06-24T08:34:10Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/graphql","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
```

If I can find out more information, I'll be sure to post it here.

**Comment by illagrenan** [comment]
I increased the `--write-timeout` as well as the timeout on the client side. Now my re-import seems to be running perfectly fine. 

For me, this issue can be closed. Thanks for your time!
