### ISSUE TITLE
Crash on data upload

### ISSUE THREAD

**Issue by generall** [semi-technologies/weaviate#2066]
Hi! I am trying to upload vectors as fast as possible into fresh weaviate instance.

I am using:

```
    @classmethod
    def upload_batch(
        cls, ids: List[int], vectors: List[list], metadata: List[Optional[dict]]
    ):
        for id_, vector, data_object in zip(ids, vectors, metadata):
            cls.client.batch.add_data_object(
                data_object=data_object or {},
                class_name=WEAVIATE_CLASS_NAME,
                uuid=uuid.UUID(int=id_).hex,
                vector=vector,
            )
        cls.client.batch.create_objects()
```

with `batch_size=10000` - as suggested in https://github.com/semi-technologies/weaviate-benchmarking/blob/main/benchmark-scripts/src/functions.py#L187
And I am also trying to upload data in parallel.

and sometimes getting the following error:

```
goroutine 8279138 [running]:
net/http.(*conn).serve.func1(0xc20fc068c0)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x1197bc0, 0xc1184c6050)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreateOK).WriteResponse(0xc03902c5d0, 0x15a8428, 0xc03a6c0540, 0x1594500, 0x147efd0)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create_responses.go:70 +0x14d
github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc043526300, 0x15a8428, 0xc03a6c0540, 0xc00a9c0700, 0xc000791020, 0x1, 0x1, 0xc03a6d2400, 0x1168b40, 0xc03902c5d0)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x579
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreate).ServeHTTP(0xc00054e3c0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2600)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create.go:90 +0x3a6
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2500)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0007fb710, 0x15a8428, 0xc03a6c0540, 0xc03a6d2500)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeSetupMiddlewares.func1.1(0x15a8428, 0xc03a6c0540, 0xc03a6d2500)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:42 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0435464a0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2500)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x359
net/http.HandlerFunc.ServeHTTP(0xc043ac0620, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc043acabc0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc043acac00, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc043ac0740, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc043ad5140, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddLogging.func1.1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:116 +0x2f4
net/http.HandlerFunc.ServeHTTP(0xc043ad5170, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addPreflight.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:150 +0x74
net/http.HandlerFunc.ServeHTTP(0xc043acdcc8, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:185 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc043acdce0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addHandleRoot.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:57 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc043acdcf8, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:78 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc043ad51a0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1(0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:168 +0x2e4
net/http.HandlerFunc.ServeHTTP(0xc043acdd10, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc00089c8c0, 0x15a8428, 0xc03a6c0540, 0xc03a6d2300)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc20fc068c0, 0x15ac9b8, 0xc20fb59340)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
2022/07/31 03:20:39 http: panic serving 10.0.0.2:38286: write tcp 172.19.0.2:8090->10.0.0.2:38286: write: broken pipe
goroutine 8279107 [running]:
net/http.(*conn).serve.func1(0xc20da9c500)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x1197bc0, 0xc0000c6320)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreateOK).WriteResponse(0xc04c1d9260, 0x15a8428, 0xc03a6c0000, 0x1594500, 0x147efd0)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create_responses.go:70 +0x14d
github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc043526300, 0x15a8428, 0xc03a6c0000, 0xc00040f000, 0xc000791020, 0x1, 0x1, 0xc0084b0500, 0x1168b40, 0xc04c1d9260)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x579
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreate).ServeHTTP(0xc00054e3c0, 0x15a8428, 0xc03a6c0000, 0xc0084b0800)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create.go:90 +0x3a6
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0007fb710, 0x15a8428, 0xc03a6c0000, 0xc0084b0700)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeSetupMiddlewares.func1.1(0x15a8428, 0xc03a6c0000, 0xc0084b0700)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:42 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0435464a0, 0x15a8428, 0xc03a6c0000, 0xc0084b0700)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x359
net/http.HandlerFunc.ServeHTTP(0xc043ac0620, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc043acabc0, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc043acac00, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc043ac0740, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc043ad5140, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddLogging.func1.1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:116 +0x2f4
net/http.HandlerFunc.ServeHTTP(0xc043ad5170, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addPreflight.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:150 +0x74
net/http.HandlerFunc.ServeHTTP(0xc043acdcc8, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:185 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc043acdce0, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addHandleRoot.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:57 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc043acdcf8, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:78 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc043ad51a0, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1(0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:168 +0x2e4
net/http.HandlerFunc.ServeHTTP(0xc043acdd10, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc00089c8c0, 0x15a8428, 0xc03a6c0000, 0xc0084b0400)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc20da9c500, 0x15ac9b8, 0xc20dba21c0)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
2022/07/31 03:20:40 http: panic serving 10.0.0.2:38290: write tcp 172.19.0.2:8090->10.0.0.2:38290: write: broken pipe
goroutine 8279113 [running]:
net/http.(*conn).serve.func1(0xc20da9c640)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x1197bc0, 0xc20ac680a0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreateOK).WriteResponse(0xc0684d7878, 0x15a8428, 0xc0073228c0, 0x1594500, 0x147efd0)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create_responses.go:70 +0x14d
github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc043526300, 0x15a8428, 0xc0073228c0, 0xc00a9c0c00, 0xc000791020, 0x1, 0x1, 0xc0a25a7b00, 0x1168b40, 0xc0684d7878)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x579
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch.(*BatchObjectsCreate).ServeHTTP(0xc00054e3c0, 0x15a8428, 0xc0073228c0, 0xc0a25a7d00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/batch/batch_objects_create.go:90 +0x3a6
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7c00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0007fb710, 0x15a8428, 0xc0073228c0, 0xc0a25a7c00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeSetupMiddlewares.func1.1(0x15a8428, 0xc0073228c0, 0xc0a25a7c00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:42 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0435464a0, 0x15a8428, 0xc0073228c0, 0xc0a25a7c00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x359
net/http.HandlerFunc.ServeHTTP(0xc043ac0620, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc043acabc0, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc043acac00, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc043ac0740, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc043ad5140, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddLogging.func1.1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:116 +0x2f4
net/http.HandlerFunc.ServeHTTP(0xc043ad5170, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addPreflight.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:150 +0x74
net/http.HandlerFunc.ServeHTTP(0xc043acdcc8, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:185 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc043acdce0, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addHandleRoot.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:57 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc043acdcf8, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:78 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc043ad51a0, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1(0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:168 +0x2e4
net/http.HandlerFunc.ServeHTTP(0xc043acdd10, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc00089c8c0, 0x15a8428, 0xc0073228c0, 0xc0a25a7a00)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc20da9c640, 0x15ac9b8, 0xc20dba2440)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
```

**Comment by etiennedi** [comment]
Hello Andrey, nice to see you here ;-) 

> and sometimes getting the following error:

## Cause
The first stack trace seems to begin one line too late, it only contains the stack trace itself, but looks like it's missing the error/message/panic that caused it. However, the second one does, so I assume both are the same:

```
2022/07/31 03:20:39 http: panic serving 10.0.0.2:38286: write tcp 172.19.0.2:8090->10.0.0.2:38286: write: broken pipe
```

The broken pipe indicates that the client has already closed the connection (most likely due to a client-side timeout), and Weaviate tries to write the response for the batch creation onto the closed (or reset) connection. The default behavior of the Go HTTP server is to catch these TCP-level panics, and then print them to stdout with the stack trace attached. Admittedly, this is super confusing, which is why we have addressed this in this [PR](https://github.com/semi-technologies/weaviate/pull/2047) which will be part of the next release.

Without knowing too much about your setup, I would guess that sending parallel batches of 10,000 occasionally leads to individual batches taking longer than the client-side configured timeout. 

## Potential Remedies

### Smaller Batch Size
The main motivation of a large batch size is to make sure that Weaviate can parallelize the contents of the batch and that individual threads don't run out of work. Assuming you're not running with 1000s of CPU cores, that should also be achievable with a smaller batch size, e.g. 1000. The more parallel feeders you have the more parallelization happens anyway, so the benefit of a large batch becomes less and less. E.g. 10 feeders with batch size 500 will probably be faster than 1 feeder with batch size 5000. But the shorter batches lead to shorter-running requests which generally make life easier.

### Larger Timeouts
*Client-side*
You can of course also address this from the other side, you can increase the timeouts. The python client defaults to 20s, which can be adjusted like so (e.g. setting it to 60s):

```python
client = Client(
    url = 'http://localhost:8080',
    timeout_config = (60)
)
```

*Server-Side*
Note that there is also a default server-side timeout of 60s, which can be adjusted using command line arguments. For example, assuming a docker-compose config, like so:

```
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    - --read-timeout
    - 10s
    - --write-timeout
    - 120s
```

Hope that helps address those panics and their stacktraces. As mentioned above, the next release will have considerably more helpful error messages for this case.

**Comment by generall** [comment]
Hm, I am already using quite large value for the timeout. Will try smaller batches then, thanks
